server:
  port: 9081
  servlet:
    context-path: /artimo

spring:
  datasource:
    url: jdbc:mysql://39.100.150.44:3306/artimo_dev
    username: artimo
    password: h7E43G39*88!!3NR
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:sqlmap/*/*.xml, classpath:sqlmapext/*/*.xml